In [19]:
import pandas as pd

In [20]:
rbg = pd.read_excel('Research block grants time series 2021-2026.xlsx', sheet_name='Table 2', header=2)

comparators = ['University of Technology Sydney', 'Queensland University of Technology', 'Curtin University']
rbg_sub = rbg[rbg['HEP Name'].isin(comparators)]

rbg_totals = rbg_sub.groupby(['HEP Name', 'Year'])['Amount'].sum().reset_index()
rbg_totals = rbg_totals.rename(columns={'HEP Name': 'Institution', 'Amount': 'RBG_Total'})
rbg_totals

                        Institution  Year  RBG_Total
0                 Curtin University  2001   16844326
1                 Curtin University  2002   17988215
2                 Curtin University  2003   19626995
3                 Curtin University  2004   20698287
4                 Curtin University  2005   21733140
..                              ...   ...        ...
73  University of Technology Sydney  2022   42575185
74  University of Technology Sydney  2023   44449378
75  University of Technology Sydney  2024   47084992
76  University of Technology Sydney  2025   48273626
77  University of Technology Sydney  2026   50346535

[78 rows x 3 columns]

In [21]:
comp = pd.read_excel('Perturbed Award Course Completions Pivot Table 2024.xlsx', sheet_name='Pivot', skiprows=24)

comp['State'] = comp['State'].ffill()                                   
comp = comp.dropna(subset=['Institution'])                              
comp = comp[comp['Institution'] != 'Non-University Higher Education Providers']  

comp_sub = comp[comp['Institution'].isin(comparators)]
comp_long = comp_sub.melt(
    id_vars=['State', 'Institution'],
    value_vars=[2020, 2021, 2022, 2023, 2024],
    var_name='Year', value_name='Completions'
)
comp_long

                State                          Institution  Year  Completions
0     New South Wales      University of Technology Sydney  2020        11960
1          Queensland  Queensland University of Technology  2020        10943
2   Western Australia                    Curtin University  2020         9787
3     New South Wales      University of Technology Sydney  2021         8411
4          Queensland  Queensland University of Technology  2021        12200
5   Western Australia                    Curtin University  2021        10076
6     New South Wales      University of Technology Sydney  2022        11273
7          Queensland  Queensland University of Technology  2022        11361
8   Western Australia                    Curtin University  2022        10225
9     New South Wales      University of Technology Sydney  2023        10453
10         Queensland  Queensland University of Technology  2023        10535
11  Western Australia                    Curtin University  2023        10255
12    New South Wales      University of Technology Sydney  2024        12318
13         Queensland  Queensland University of Technology  2024        11488
14  Western Australia                    Curtin University  2024        11834

In [22]:
merged = pd.merge(rbg_totals, comp_long, on=['Institution', 'Year'])
merged['RBG_per_Completion'] = merged['RBG_Total'] / merged['Completions']
merged.sort_values(['Institution', 'Year'])

,Institution,Year,RBG_Total,State,Completions,RBG_per_Completion
0,Curtin University,2020,48012801,Western Australia,9787,4905.773066
1,Curtin University,2021,72099626,Western Australia,10076,7155.580191
2,Curtin University,2022,50218883,Western Australia,10225,4911.382200
3,Curtin University,2023,50684099,Western Australia,10255,4942.379230
4,Curtin University,2024,54457752,Western Australia,11834,4601.804293
5,Queensland University of Technology,2020,52474025,Queensland,10943,4795.213835
6,Queensland University of Technology,2021,72857176,Queensland,12200,5971.899672
7,Queensland University of Technology,2022,48384663,Queensland,11361,4258.838395
8,Queensland University of Technology,2023,52786093,Queensland,10535,5010.545135
9,Queensland University of Technology,2024,56855908,Queensland,11488,4949.156337
10,University of Technology Sydney,2020,33010743,New South Wales,11960,2760.095569
11,University of Technology Sydney,2021,54204501,New South Wales,8411,6444.477589
12,University of Technology Sydney,2022,42575185,New South Wales,11273,3776.739555
13,University of Technology Sydney,2023,44449378,New South Wales,10453,4252.308237
14,University of Technology Sydney,2024,47084992,New South Wales,12318,3822.454295